// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partner-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Partner struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TradingName          string   `protobuf:"bytes,2,opt,name=trading_name,json=tradingName,proto3" json:"trading_name,omitempty"`
	OwnerName            string   `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Document             string   `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	CoverageArea         []byte   `protobuf:"bytes,5,opt,name=coverage_area,json=coverageArea,proto3" json:"coverage_area,omitempty"`
	Address              []byte   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partner) Reset()         { *m = Partner{} }
func (m *Partner) String() string { return proto.CompactTextString(m) }
func (*Partner) ProtoMessage()    {}
func (*Partner) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{0}
}

func (m *Partner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner.Unmarshal(m, b)
}
func (m *Partner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner.Marshal(b, m, deterministic)
}
func (m *Partner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner.Merge(m, src)
}
func (m *Partner) XXX_Size() int {
	return xxx_messageInfo_Partner.Size(m)
}
func (m *Partner) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner.DiscardUnknown(m)
}

var xxx_messageInfo_Partner proto.InternalMessageInfo

func (m *Partner) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Partner) GetTradingName() string {
	if m != nil {
		return m.TradingName
	}
	return ""
}

func (m *Partner) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Partner) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

func (m *Partner) GetCoverageArea() []byte {
	if m != nil {
		return m.CoverageArea
	}
	return nil
}

func (m *Partner) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Partner              *Partner `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetPartner() *Partner {
	if m != nil {
		return m.Partner
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Partner              *Partner `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetPartner() *Partner {
	if m != nil {
		return m.Partner
	}
	return nil
}

type GetRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Partner              *Partner `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetResponse) GetPartner() *Partner {
	if m != nil {
		return m.Partner
	}
	return nil
}

type FilterLocationRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterLocationRequest) Reset()         { *m = FilterLocationRequest{} }
func (m *FilterLocationRequest) String() string { return proto.CompactTextString(m) }
func (*FilterLocationRequest) ProtoMessage()    {}
func (*FilterLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{5}
}

func (m *FilterLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterLocationRequest.Unmarshal(m, b)
}
func (m *FilterLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterLocationRequest.Marshal(b, m, deterministic)
}
func (m *FilterLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterLocationRequest.Merge(m, src)
}
func (m *FilterLocationRequest) XXX_Size() int {
	return xxx_messageInfo_FilterLocationRequest.Size(m)
}
func (m *FilterLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterLocationRequest proto.InternalMessageInfo

func (m *FilterLocationRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FilterLocationRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *FilterLocationRequest) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type FilterLocationResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Partners             []*Partner `protobuf:"bytes,2,rep,name=partners,proto3" json:"partners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FilterLocationResponse) Reset()         { *m = FilterLocationResponse{} }
func (m *FilterLocationResponse) String() string { return proto.CompactTextString(m) }
func (*FilterLocationResponse) ProtoMessage()    {}
func (*FilterLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b714c9323e46c86, []int{6}
}

func (m *FilterLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterLocationResponse.Unmarshal(m, b)
}
func (m *FilterLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterLocationResponse.Marshal(b, m, deterministic)
}
func (m *FilterLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterLocationResponse.Merge(m, src)
}
func (m *FilterLocationResponse) XXX_Size() int {
	return xxx_messageInfo_FilterLocationResponse.Size(m)
}
func (m *FilterLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterLocationResponse proto.InternalMessageInfo

func (m *FilterLocationResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FilterLocationResponse) GetPartners() []*Partner {
	if m != nil {
		return m.Partners
	}
	return nil
}

func init() {
	proto.RegisterType((*Partner)(nil), "v1.Partner")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "v1.GetResponse")
	proto.RegisterType((*FilterLocationRequest)(nil), "v1.FilterLocationRequest")
	proto.RegisterType((*FilterLocationResponse)(nil), "v1.FilterLocationResponse")
}

func init() { proto.RegisterFile("partner-service.proto", fileDescriptor_4b714c9323e46c86) }

var fileDescriptor_4b714c9323e46c86 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xed, 0x6a, 0xdb, 0x30,
	0x14, 0xc5, 0xf6, 0x96, 0x8f, 0xeb, 0x24, 0xcb, 0x04, 0xd9, 0x3c, 0xc3, 0xc0, 0xf3, 0x18, 0xcb,
	0x9f, 0x18, 0x92, 0xc1, 0xfe, 0x6f, 0x83, 0xac, 0x85, 0xb6, 0x04, 0xe7, 0x01, 0x82, 0x6a, 0x5f,
	0x8c, 0x21, 0x91, 0x5c, 0x59, 0x71, 0xe9, 0x8b, 0xf5, 0x1d, 0xfa, 0x56, 0xc5, 0xb2, 0xe4, 0xb6,
	0x21, 0xf9, 0xd3, 0xfe, 0x93, 0xce, 0x39, 0xba, 0x3e, 0xf7, 0xdc, 0x6b, 0x98, 0x14, 0x54, 0x48,
	0x86, 0x62, 0x56, 0xa2, 0xa8, 0xf2, 0x04, 0xa3, 0x42, 0x70, 0xc9, 0x89, 0x5d, 0xcd, 0xc3, 0x7b,
	0x0b, 0xba, 0xab, 0x86, 0x25, 0x23, 0xb0, 0xf3, 0xd4, 0xb3, 0x02, 0x6b, 0xea, 0xc4, 0x76, 0x9e,
	0x92, 0x6f, 0x30, 0x90, 0x82, 0xa6, 0x39, 0xcb, 0x36, 0x8c, 0xee, 0xd0, 0xb3, 0x03, 0x6b, 0xda,
	0x8f, 0x5d, 0x8d, 0x5d, 0xd1, 0x1d, 0x92, 0xaf, 0x00, 0xfc, 0x96, 0xa1, 0x68, 0x04, 0x8e, 0x12,
	0xf4, 0x15, 0xa2, 0x68, 0x1f, 0x7a, 0x29, 0x4f, 0xf6, 0x3b, 0x64, 0xd2, 0x7b, 0xa7, 0xc8, 0xf6,
	0x4e, 0xbe, 0xc3, 0x30, 0xe1, 0x15, 0x0a, 0x9a, 0xe1, 0x86, 0x0a, 0xa4, 0xde, 0xfb, 0xc0, 0x9a,
	0x0e, 0xe2, 0x81, 0x01, 0xff, 0x08, 0xa4, 0xc4, 0x83, 0x2e, 0x4d, 0x53, 0x81, 0x65, 0xe9, 0x75,
	0x14, 0x6d, 0xae, 0xe1, 0x19, 0x0c, 0xff, 0x09, 0xa4, 0x12, 0x63, 0xbc, 0xd9, 0x63, 0x29, 0xc9,
	0x18, 0x1c, 0x5a, 0xe4, 0xca, 0x7e, 0x3f, 0xae, 0x8f, 0xe4, 0x07, 0x74, 0x75, 0xe3, 0xca, 0xba,
	0xbb, 0x70, 0xa3, 0x6a, 0x1e, 0xe9, 0x6e, 0x63, 0xc3, 0x85, 0xe7, 0x30, 0x32, 0x95, 0xca, 0x82,
	0xb3, 0x12, 0x5f, 0x5f, 0x2a, 0x02, 0xf8, 0x8f, 0xf2, 0xb4, 0xa3, 0x26, 0x61, 0xdb, 0x24, 0x1c,
	0x2e, 0xc1, 0x55, 0xfa, 0xb7, 0x7e, 0xf7, 0x12, 0x26, 0xcb, 0x7c, 0x2b, 0x51, 0x5c, 0xf0, 0x84,
	0xca, 0x9c, 0xb3, 0xd3, 0x16, 0xc6, 0xe0, 0x6c, 0xa9, 0x54, 0xd5, 0xac, 0xb8, 0x3e, 0x2a, 0x84,
	0x65, 0x6a, 0x78, 0x35, 0xc2, 0xb2, 0x70, 0x0d, 0x9f, 0x0e, 0xcb, 0x9d, 0x74, 0xf8, 0x13, 0x7a,
	0xda, 0x45, 0xe9, 0xd9, 0x81, 0x73, 0x68, 0xb1, 0x25, 0x17, 0x0f, 0x16, 0x8c, 0x34, 0xba, 0x6e,
	0xd6, 0x90, 0xfc, 0x36, 0x33, 0x34, 0x1b, 0xf8, 0xb1, 0x7e, 0xfa, 0x62, 0xac, 0x3e, 0x79, 0x0e,
	0x69, 0x17, 0x33, 0x15, 0x73, 0xbb, 0xb6, 0xb5, 0xe2, 0x29, 0x76, 0xff, 0x43, 0x7b, 0xd7, 0xf2,
	0x15, 0x7c, 0x6e, 0xda, 0xd1, 0x2f, 0xfe, 0xde, 0x99, 0xbe, 0xc8, 0x97, 0x5a, 0x7b, 0x34, 0x3a,
	0xdf, 0x3f, 0x46, 0x35, 0x15, 0xaf, 0x3b, 0xea, 0x07, 0xfa, 0xf5, 0x18, 0x00, 0x00, 0xff, 0xff,
	0xdc, 0xd5, 0x4c, 0x51, 0x59, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PartnerServiceClient is the client API for PartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PartnerServiceClient interface {
	CreatePartner(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetPartner(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	FilterPartnerByLocation(ctx context.Context, in *FilterLocationRequest, opts ...grpc.CallOption) (*FilterLocationResponse, error)
}

type partnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerServiceClient(cc grpc.ClientConnInterface) PartnerServiceClient {
	return &partnerServiceClient{cc}
}

func (c *partnerServiceClient) CreatePartner(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.PartnerService/CreatePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetPartner(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/v1.PartnerService/GetPartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) FilterPartnerByLocation(ctx context.Context, in *FilterLocationRequest, opts ...grpc.CallOption) (*FilterLocationResponse, error) {
	out := new(FilterLocationResponse)
	err := c.cc.Invoke(ctx, "/v1.PartnerService/FilterPartnerByLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerServiceServer is the server API for PartnerService service.
type PartnerServiceServer interface {
	CreatePartner(context.Context, *CreateRequest) (*CreateResponse, error)
	GetPartner(context.Context, *GetRequest) (*GetResponse, error)
	FilterPartnerByLocation(context.Context, *FilterLocationRequest) (*FilterLocationResponse, error)
}

// UnimplementedPartnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPartnerServiceServer struct {
}

func (*UnimplementedPartnerServiceServer) CreatePartner(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartner not implemented")
}
func (*UnimplementedPartnerServiceServer) GetPartner(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartner not implemented")
}
func (*UnimplementedPartnerServiceServer) FilterPartnerByLocation(ctx context.Context, req *FilterLocationRequest) (*FilterLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterPartnerByLocation not implemented")
}

func RegisterPartnerServiceServer(s *grpc.Server, srv PartnerServiceServer) {
	s.RegisterService(&_PartnerService_serviceDesc, srv)
}

func _PartnerService_CreatePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).CreatePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PartnerService/CreatePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).CreatePartner(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetPartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetPartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PartnerService/GetPartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetPartner(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_FilterPartnerByLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).FilterPartnerByLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PartnerService/FilterPartnerByLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).FilterPartnerByLocation(ctx, req.(*FilterLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PartnerService",
	HandlerType: (*PartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePartner",
			Handler:    _PartnerService_CreatePartner_Handler,
		},
		{
			MethodName: "GetPartner",
			Handler:    _PartnerService_GetPartner_Handler,
		},
		{
			MethodName: "FilterPartnerByLocation",
			Handler:    _PartnerService_FilterPartnerByLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partner-service.proto",
}
